# Railway (Nixpacks) build plan

[start]
cmd = "gunicorn dataanalyzer.wsgi:application --bind 0.0.0.0:${PORT}"

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]
